# You define a name for this workflow
name: CI/CD
on: 
# We will use this workflow when we create a pull request to the main branch 
  pull_request:
    branches: [main]
  jobs:
    build: 
      runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: use nodejs 20.12.2
# GitHub actions node setup for NodeJS
        uses: actions/setup-node@v3
        with: 
# Use x, so that you will not need to update or upgrade all the node versions everytime node has a new version    
          node-version: 20.x
# Installs NPM packages than npm by using ci          
      - run: npm ci
# We build our code here & only use this command if it exists inside our package.json
      - run: npm run build --if-present 
# Run unit tests by adding npm test      
#      - run: npm test       
  deplay: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3 
      - uses: akhileshns/heroku-deploy@v3.12.127
        with: 
          heroku_api_key: